"""rox_parser package."""

from .core import Parameter, RoxDocument, parse_file, parse_parameters, parse_text
from .dependencies import DependencyEdge, build_dependency_rows, extract_dependencies
from .dot import (
    GraphvizError,
    GraphvizNotInstalledError,
    GraphvizRenderError,
    build_graph_dot,
    build_graph_svg,
    export_graph_to_dot,
    export_graph_to_svg,
    render_dot_to_svg,
)
from .graph import (
    DependencyGraph,
    GraphEdge,
    GraphNode,
    build_dependency_graph,
    build_graph_nodes,
    build_graph_rows,
    reduce_dependency_graph,
)
from .report import ReportRow, build_report_html, build_report_rows
from .workflow import (
    WorkflowDocument,
    WorkflowQuickAction,
    WorkflowWarning,
    WorkflowXmlSection,
    extract_workflow_definition_text,
    parse_workflow_from_document,
    parse_workflow_from_text,
    parse_workflow_text,
)
from .workflow_graph import (
    WorkflowBlockProperty,
    WorkflowGraph,
    WorkflowGraphEdge,
    WorkflowGraphNode,
    WorkflowPropertyGroup,
    build_workflow_graph,
)
from .workflow_report import build_workflow_report_html
from .workflow_trigger import (
    WorkflowTriggerCondition,
    WorkflowTriggerEvents,
    WorkflowTriggerGroup,
    WorkflowTriggerModel,
    WorkflowTriggerProperty,
    build_workflow_trigger_model,
)

__all__ = [
    "DependencyGraph",
    "DependencyEdge",
    "GraphvizError",
    "GraphvizNotInstalledError",
    "GraphvizRenderError",
    "GraphEdge",
    "GraphNode",
    "Parameter",
    "ReportRow",
    "RoxDocument",
    "WorkflowDocument",
    "WorkflowBlockProperty",
    "WorkflowGraph",
    "WorkflowGraphEdge",
    "WorkflowGraphNode",
    "WorkflowPropertyGroup",
    "WorkflowQuickAction",
    "WorkflowTriggerCondition",
    "WorkflowTriggerEvents",
    "WorkflowTriggerGroup",
    "WorkflowTriggerModel",
    "WorkflowTriggerProperty",
    "WorkflowWarning",
    "WorkflowXmlSection",
    "build_dependency_rows",
    "build_dependency_graph",
    "build_graph_dot",
    "build_graph_svg",
    "build_graph_nodes",
    "build_graph_rows",
    "build_report_html",
    "build_report_rows",
    "build_workflow_graph",
    "build_workflow_report_html",
    "build_workflow_trigger_model",
    "export_graph_to_dot",
    "export_graph_to_svg",
    "extract_workflow_definition_text",
    "extract_dependencies",
    "parse_file",
    "parse_parameters",
    "parse_text",
    "parse_workflow_from_document",
    "parse_workflow_from_text",
    "parse_workflow_text",
    "reduce_dependency_graph",
    "render_dot_to_svg",
]
